#!/bin/sh
cp -p ghd /etc/init.d/ghd
cd /etc/rc0.d
		ln -s ../init.d/ghd K20ghd
cd /etc/rc1.d
		ln -s ../init.d/ghd K20ghd
cd /etc/rc2.d
		ln -s ../init.d/ghd S20ghd
cd /etc/rc3.d
		ln -s ../init.d/ghd S20ghd
cd /etc/rc4.d
		ln -s ../init.d/ghd S20ghd
cd /etc/rc5.d
		ln -s ../init.d/ghd S20ghd
cd /etc/rc6.d
		ln -s ../init.d/ghd K20ghd
